server:
  port: 8006

spring:
  application:
    name: consul-provider-payment
  cloud:
    # 注册到consul
    consul:
      host: 172.16.201.128
      port: 8500
      discovery:
        service-name: ${spring.application.name}